---
# TODO: Only execute if swap space is not already available
- name: create swap file
  shell: dd if=/dev/zero of=/swapfile bs=256M count=4
  become: yes
  register: cmd
  failed_when:
    - cmd.rc != 0
    - "'Text file busy' not in cmd.stderr"

- name: chmod swap file
  shell: chmod 600 /swapfile
  become: yes

- name: mkswap swap file
  shell: mkswap /swapfile
  become: yes
  register: cmd
  failed_when:
    - cmd.rc != 0
    - "'error: /swapfile is mounted; will not make swapspace' not in cmd.stderr"

- name: swapon
  shell: swapon /swapfile
  become: yes
  register: cmd
  failed_when:
    - cmd.rc != 0
    - "'swapon failed: Device or resource busy' not in cmd.stderr"

- name: add swapfile to /etc/fstab
  # only add the line: '/swapfile swap swap defaults 0 0' if it is not already present
  shell: grep -qxF '/swapfile swap swap defaults 0 0' /etc/fstab || sed -i.bak 's/#/#\n\/swapfile swap swap defaults 0 0/g' /etc/fstab
  become: yes