version: "3.7"
services:

  public_api:
      image: localhost:5443/public_api:latest
      volumes:
        - ${WORKING_DIR:-/mnt/efs}/public_api/app:/app
      networks:
        - traefik-public
        - auth
        - services
      restart: unless-stopped
      deploy:
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.http.services.public-api.loadbalancer.server.port=80
          - traefik.http.routers.public-api.rule=Host(`api.example.com`)
          - traefik.http.routers.public-api.entrypoints=http
          # HTTPS
          - traefik.http.middlewares.public-api-redirect-sec.redirectscheme.scheme=https
          - traefik.http.routers.public-api.middlewares=public-api-redirect-sec
          - traefik.http.routers.public-api-sec.rule=Host(`api.example.com`)
          - traefik.http.routers.public-api-sec.entrypoints=https
          - traefik.http.routers.public-api-sec.tls.certResolver=dnsCertResolver
          - traefik.http.routers.public-api-sec.tls.domains[0].main=*.example.com
        replicas: 2
        placement:
          constraints:
            - node.labels.type!=swarm-leader

  auth:
    image: localhost:5443/auth:latest
    volumes:
      - ${WORKING_DIR:-/mnt/efs}/auth/app:/app
    networks:
      - traefik-public
      - auth
    restart: unless-stopped
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type!=swarm-leader
  redis:
    image: redislabs/rejson
    volumes:
      - ${WORKING_DIR:-/mnt/efs}/auth/redis:/redis
    networks:
      - auth
    working_dir: /redis/data
    command: ["redis-server", "/redis/redis.config"]
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type!=swarm-leader


  #couchdb:
  #  image: couchdb:latest
  #  container_name: couchdb
  #  ports:
  #    - "5984:5984"
  #  volumes:
  #    - ${WORKING_DIR:-/mnt/efs}/couchdb/data:/opt/couchdb/data
  #  networks:
  #    - services
  #    - pyspider
  #  environment:
  #    - COUCHDB_NAME=couchdb
  #    - COUCHDB_PORT_5984_TCP_ADDR=couchdb
  #    - COUCHDB_PORT_5984_TCP_PORT=5984
  #    - COUCHDB_USER=user
  #    - COUCHDB_PASSWORD=password
  #  deploy:
  #    replicas: 2

  #webservice:
  #  build:
  #    context: ./webservice
  #    dockerfile: Dockerfile
  #  image: localhost:5000/webservice:latest
  #  container_name: webservice
  #  ports:
  #    - "5000:5000" # Must be the same as the node port (else you'll get a blank page because static resources will 404)
  #    - "8000:8000"
  #  volumes:
  #    - ${WORKING_DIR:-/mnt/efs}/webservice/app:/app
  #    - /app/node_modules # stops /app/node_modules getting overwritten with the hosts node_modules
  #  networks:
  #    - traefik-public
  #    - auth
  #    - services # backend needs connection to couchDB for watchlist updates for example
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.webservice.rule=Host(`localhost`)"
  #    - "traefik.http.routers.webservice.entrypoints=http"
  #  restart: unless-stopped


networks:
  traefik-public:
    name: traefik-public
    external: true
  registry:
    name: registry
    external: true
  auth:
    name: auth
    external: true
  services:
    name: services
    external: true
