# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'monitoring'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      # the targets listed here must match the service names from the docker-compose file
      # Eg: ['manager-001:9100','worker-001:9100']
      - targets: $$node-exporter-services$$

  - job_name: 'cadvisor'
    static_configs:
      # the targets listed here must match the service names from the docker-compose file
      # Eg: ['docker-manager-001:8080','docker-worker-001:8080']
      - targets: $$cadvisor-services$$
