---
- name: deploy registry stack
  shell: export $(cat {{ working_dir }}/.env) > /dev/null 2>&1 ; docker stack deploy --compose-file {{ working_dir }}/dockerfiles/docker-compose-registry.yml docker-registry
