---
- name: create .htpasswd
  shell: 'htpasswd -Bbn {{ registry_username }} {{ registry_password }} > {{ working_dir }}/registry/auth/htpasswd'
  #shell: 'docker run --rm --entrypoint htpasswd registry:2 -Bbn {{ registry_username }} {{ registry_password }} > {{ working_dir }}/registry/auth/htpasswd'
