---
- name: create {{ working_dir }}/traefik/auth/.htpasswd with default user '{{ traefik_username }}'
  # '$' must be escaped
  shell: echo {{ traefik_username }}:{{ traefik_password }} > {{ working_dir }}/traefik/auth/.htpasswd
