---
- name: copy public_api
  copy:
    src: ../../../public_api/
    dest: '{{ working_dir }}/test/public_api/'
    owner: '{{ ansible_user }}'

- name: copy auth/app
  copy:
    src: ../../../auth/app/
    dest: '{{ working_dir }}/test/auth/app/'
    owner: '{{ ansible_user }}'

- name: copy auth/redis/redis.config
  copy:
    src: ../../../auth/redis/redis.config
    dest: '{{ working_dir }}/test/auth/redis/redis.config'
    owner: '{{ ansible_user }}'

- name: copy newswatcher/app
  copy:
    src: ../../../newswatcher/app/
    dest: '{{ working_dir }}/test/newswatcher/app/'
    owner: '{{ ansible_user }}'

# The compose file wil be used by jenkins later so may as well copy it over now
- name: copy docker-compose
  copy:
    src: ../../../docker-compose.yml
    dest: '{{ working_dir }}/dockerfiles'
    owner: '{{ ansible_user }}'

- name: copy docker-compose-test
  copy:
    src: ../../../docker-compose-test.yml
    dest: '{{ working_dir }}/dockerfiles'
    owner: '{{ ansible_user }}'

- name: chmod the compose file
  shell: chmod 644 {{ working_dir }}/dockerfiles/docker-compose.yml

- name: chmod the test compose file
  shell: chmod 644 {{ working_dir }}/dockerfiles/docker-compose-test.yml