---
# We assume the the compose file has already been copied here by Jenkins after a git push
- name: deploy the test stack
  shell: docker stack deploy --with-registry-auth --compose-file {{ working_dir }}/dockerfiles/docker-compose-test.yml test-stack
  environment:
    WORKING_DIR: '{{ working_dir }}'
