export const SAVE_ACCESS_TOKEN = 'SAVE_ACCESS_TOKEN';

export const FETCH_USER_DOC_BEGIN   = 'FETCH_USER_DOC_BEGIN';
export const FETCH_USER_DOC_SUCCESS = 'FETCH_USER_DOC_SUCCESS';
export const FETCH_USER_DOC_FAILURE = 'FETCH_USER_DOC_FAILURE';

export const UPDATE_USER_DOC_BEGIN = "UPDATE_USER_DOC_BEGIN";
export const UPDATE_USER_DOC_SUCCESS = "UPDATE_USER_DOC_SUCCESS";
export const UPDATE_USER_DOC_FAILURE = "UPDATE_USER_DOC_FAILURE";
