---
- name: ensure {{ working_dir }} exists
  file:
    path: "{{ working_dir }}"
    state: directory

- name: ensure {{ working_dir }}/dockerfiles exists
  file:
    path: "{{ working_dir }}/dockerfiles"
    state: directory

- name: ensure {{ working_dir }}/public_api/app exists
  file:
    path: "{{ working_dir }}/test/public_api/app"
    state: directory

- name: ensure {{ working_dir }}/auth/app exists
  file:
    path: "{{ working_dir }}/test/auth/app"
    state: directory

- name: ensure {{ working_dir }}/auth/redis exists
  file:
    path: "{{ working_dir }}/auth/redis"
    state: directory

- name: ensure {{ working_dir }}/auth/redis/data exists
  file:
    path: "{{ working_dir }}/auth/redis/data"
    state: directory
