# This is a 'production' Dockerfile that builds and deploys - will not auto-update changes

FROM node:10 AS builder

# Create app directory
WORKDIR /app

COPY app/ ./

RUN npm install
RUN npm i -g foreman

# If you are building your code for production
# RUN npm ci --only=production

RUN make build


# production environment
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]